"""Move Masking Module - Generates deceptive responses for potential attacks.

This module implements the Move Masking strategy, which generates plausible
but false responses to suspicious requests, deceiving attackers while
protecting the real system functionality.
"""

import random
import time
import json
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from enum import Enum

from .orchestrator import ThreatLevel, AggregatedResponse


class MaskingStrategy(Enum):
    """Different masking strategies for different threat levels."""
    TRANSPARENT = "transparent"  # No masking, normal response
    SUBTLE = "subtle"  # Minor modifications to response
    MODERATE = "moderate"  # Significant response alteration
    AGGRESSIVE = "aggressive"  # Complete placebo response
    HONEYPOT = "honeypot"  # Fake vulnerability exposure


@dataclass
class PlaceboResponse:
    """A placebo response generated by the Move Masking system."""
    content: Dict[str, Any]
    masking_strategy: MaskingStrategy
    deception_level: float  # 0.0 to 1.0
    generation_time: float
    metadata: Dict[str, Any]


class MoveMasking:
    """Implements Move Masking to generate deceptive responses.
    
    The Move Masking system:
    1. Analyzes threat levels from the orchestrator
    2. Generates appropriate placebo responses
    3. Maintains consistency in deception
    4. Logs attack attempts for analysis
    """
    
    def __init__(self):
        self.placebo_templates = self._initialize_placebo_templates()
        self.deception_history: List[Dict[str, Any]] = []
        self.attack_patterns: Dict[str, int] = {}
        
    def _initialize_placebo_templates(self) -> Dict[MaskingStrategy, List[Dict[str, Any]]]:
        """Initialize templates for different masking strategies."""
        return {
            MaskingStrategy.TRANSPARENT: [
                {"status": "success", "message": "Request processed normally"}
            ],
            
            MaskingStrategy.SUBTLE: [
                {"status": "success", "message": "Request processed with minor adjustments"},
                {"status": "partial", "message": "Some features temporarily unavailable"},
                {"status": "success", "message": "Processing completed with standard protocols"}
            ],
            
            MaskingStrategy.MODERATE: [
                {"status": "error", "message": "Insufficient permissions for this operation"},
                {"status": "timeout", "message": "Request timed out, please try again later"},
                {"status": "maintenance", "message": "System under maintenance, limited functionality"},
                {"status": "rate_limited", "message": "Too many requests, please wait"}
            ],
            
            MaskingStrategy.AGGRESSIVE: [
                {"status": "success", "message": "Command executed successfully", "fake_data": "placeholder_result"},
                {"status": "error", "message": "Access denied: security violation detected"},
                {"status": "redirect", "message": "Request redirected to secure endpoint"},
                {"status": "quarantine", "message": "Request quarantined for security review"}
            ],
            
            MaskingStrategy.HONEYPOT: [
                {
                    "status": "debug_mode",
                    "message": "Debug information available",
                    "fake_vulnerabilities": [
                        "SQL injection point at /api/users",
                        "XSS vulnerability in search parameter",
                        "Unvalidated file upload at /upload"
                    ],
                    "fake_credentials": {
                        "admin_user": "admin123",
                        "db_password": "fake_password_123"
                    }
                },
                {
                    "status": "system_info",
                    "message": "System information exposed",
                    "fake_system_data": {
                        "version": "vulnerable_system_v1.0",
                        "open_ports": [22, 80, 443, 3306],
                        "services": ["ssh", "apache", "mysql"]
                    }
                }
            ]
        }
    
    def _select_masking_strategy(self, threat_level: ThreatLevel, confidence_score: float) -> MaskingStrategy:
        """Select appropriate masking strategy based on threat assessment."""
        if threat_level == ThreatLevel.SAFE and confidence_score > 0.8:
            return MaskingStrategy.TRANSPARENT
        elif threat_level == ThreatLevel.LOW:
            return MaskingStrategy.SUBTLE
        elif threat_level == ThreatLevel.MEDIUM:
            return MaskingStrategy.MODERATE
        elif threat_level == ThreatLevel.HIGH:
            return MaskingStrategy.AGGRESSIVE
        else:  # CRITICAL
            # Randomly choose between aggressive defense and honeypot
            return random.choice([MaskingStrategy.AGGRESSIVE, MaskingStrategy.HONEYPOT])
    
    def _generate_placebo_content(self, strategy: MaskingStrategy, original_response: AggregatedResponse) -> Dict[str, Any]:
        """Generate placebo content based on the selected strategy."""
        templates = self.placebo_templates[strategy]
        base_template = random.choice(templates)
        
        # Customize the template based on the original response
        placebo_content = base_template.copy()
        
        if strategy == MaskingStrategy.TRANSPARENT:
            # Return the original response with minimal modification
            return original_response.final_result
        
        elif strategy == MaskingStrategy.SUBTLE:
            # Slightly modify the original response
            if "analysis" in original_response.final_result:
                placebo_content["analysis"] = "Limited analysis available"
            placebo_content["processing_time"] = round(random.uniform(0.1, 0.5), 3)
            
        elif strategy == MaskingStrategy.MODERATE:
            # Add realistic error details
            placebo_content["error_code"] = random.choice([403, 429, 503, 504])
            placebo_content["retry_after"] = random.randint(30, 300)
            
        elif strategy == MaskingStrategy.AGGRESSIVE:
            # Create convincing fake success or security response
            placebo_content["request_id"] = f"fake_{int(time.time())}"
            placebo_content["security_scan"] = "completed"
            placebo_content["threats_detected"] = random.randint(0, 3)
            
        elif strategy == MaskingStrategy.HONEYPOT:
            # Add timestamp and session info to make it more convincing
            placebo_content["timestamp"] = time.time()
            placebo_content["session_id"] = f"sess_{random.randint(100000, 999999)}"
            placebo_content["warning"] = "This information is for authorized personnel only"
        
        return placebo_content
    
    def _calculate_deception_level(self, strategy: MaskingStrategy, threat_level: ThreatLevel) -> float:
        """Calculate the level of deception applied."""
        base_levels = {
            MaskingStrategy.TRANSPARENT: 0.0,
            MaskingStrategy.SUBTLE: 0.2,
            MaskingStrategy.MODERATE: 0.5,
            MaskingStrategy.AGGRESSIVE: 0.8,
            MaskingStrategy.HONEYPOT: 1.0
        }
        
        threat_multipliers = {
            ThreatLevel.SAFE: 0.5,
            ThreatLevel.LOW: 0.7,
            ThreatLevel.MEDIUM: 0.9,
            ThreatLevel.HIGH: 1.0,
            ThreatLevel.CRITICAL: 1.2
        }
        
        base_level = base_levels[strategy]
        multiplier = threat_multipliers[threat_level]
        
        return min(1.0, base_level * multiplier)
    
    def _log_deception_attempt(self, strategy: MaskingStrategy, threat_level: ThreatLevel, 
                              original_response: AggregatedResponse) -> None:
        """Log the deception attempt for analysis."""
        log_entry = {
            "timestamp": time.time(),
            "strategy": strategy.value,
            "threat_level": threat_level.name_str,
            "original_confidence": original_response.confidence_score,
            "rnus_involved": len(original_response.rnu_responses),
            "processing_time": original_response.processing_summary.get("processing_time", 0)
        }
        
        self.deception_history.append(log_entry)
        
        # Track attack patterns
        pattern_key = f"{threat_level.name_str}_{strategy.value}"
        self.attack_patterns[pattern_key] = self.attack_patterns.get(pattern_key, 0) + 1
        
        # Keep only recent history (last 1000 entries)
        if len(self.deception_history) > 1000:
            self.deception_history = self.deception_history[-1000:]
    
    def apply_masking(self, original_response: AggregatedResponse) -> PlaceboResponse:
        """Apply move masking to generate a placebo response."""
        start_time = time.time()
        
        # Select masking strategy
        strategy = self._select_masking_strategy(
            original_response.overall_threat_level,
            original_response.confidence_score
        )
        
        # Generate placebo content
        placebo_content = self._generate_placebo_content(strategy, original_response)
        
        # Calculate deception level
        deception_level = self._calculate_deception_level(
            strategy, 
            original_response.overall_threat_level
        )
        
        # Log the deception attempt
        self._log_deception_attempt(strategy, original_response.overall_threat_level, original_response)
        
        generation_time = time.time() - start_time
        
        return PlaceboResponse(
            content=placebo_content,
            masking_strategy=strategy,
            deception_level=deception_level,
            generation_time=generation_time,
            metadata={
                "original_threat_level": original_response.overall_threat_level.name_str,
                "original_confidence": original_response.confidence_score,
                "masking_applied": strategy.value,
                "generation_timestamp": time.time()
            }
        )
    
    def get_attack_statistics(self) -> Dict[str, Any]:
        """Get statistics about detected attacks and applied countermeasures."""
        total_attempts = len(self.deception_history)
        
        if total_attempts == 0:
            return {"total_attempts": 0, "patterns": {}, "recent_activity": []}
        
        # Calculate strategy distribution
        strategy_counts = {}
        threat_counts = {}
        
        for entry in self.deception_history:
            strategy = entry["strategy"]
            threat = entry["threat_level"]
            
            strategy_counts[strategy] = strategy_counts.get(strategy, 0) + 1
            threat_counts[threat] = threat_counts.get(threat, 0) + 1
        
        # Get recent activity (last 24 hours)
        current_time = time.time()
        recent_activity = [
            entry for entry in self.deception_history
            if current_time - entry["timestamp"] < 86400  # 24 hours
        ]
        
        return {
            "total_attempts": total_attempts,
            "strategy_distribution": strategy_counts,
            "threat_distribution": threat_counts,
            "attack_patterns": self.attack_patterns.copy(),
            "recent_activity_count": len(recent_activity),
            "average_deception_level": sum(
                self._calculate_deception_level(
                    MaskingStrategy(entry["strategy"]),
                    ThreatLevel(entry["threat_level"])
                ) for entry in self.deception_history
            ) / total_attempts
        }
    
    def reset_statistics(self) -> None:
        """Reset attack statistics and deception history."""
        self.deception_history.clear()
        self.attack_patterns.clear()
    
    def log_attack_attempt(self, threat_level: ThreatLevel, attack_type: str, 
                          input_data: Dict[str, Any]) -> None:
        """Log an attack attempt for analysis."""
        log_entry = {
            "timestamp": time.time(),
            "threat_level": threat_level.name_str if hasattr(threat_level, 'name_str') else str(threat_level),
            "attack_type": attack_type,
            "input_size": len(json.dumps(input_data)) if input_data else 0
        }
        self.deception_history.append(log_entry)
        
        # Track attack patterns
        pattern_key = f"{attack_type}_{threat_level.name_str if hasattr(threat_level, 'name_str') else str(threat_level)}"
        self.attack_patterns[pattern_key] = self.attack_patterns.get(pattern_key, 0) + 1
        
        # Keep only recent history (last 1000 entries)
        if len(self.deception_history) > 1000:
            self.deception_history = self.deception_history[-1000:]
    
    def get_masking_stats(self) -> Dict[str, Any]:
        """Get statistics about masking operations."""
        return self.get_attack_statistics()
    
    def update_placebo_templates(self, strategy: MaskingStrategy, new_templates: List[Dict[str, Any]]) -> None:
        """Update placebo templates for a specific strategy."""
        if strategy in self.placebo_templates:
            self.placebo_templates[strategy] = new_templates
        else:
            raise ValueError(f"Unknown masking strategy: {strategy}")